"""first, create SimVats model

Revision ID: 4d47d5775659
Revises: 
Create Date: 2021-01-28 01:15:23.463727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d47d5775659'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('contract', sa.String(length=30), nullable=True),
    sa.Column('trank_login', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vats')
    # ### end Alembic commands ###
