"""add obj, phone-str, add atrr

Revision ID: fe8537f62d5b
Revises: 
Create Date: 2021-01-28 21:21:34.490404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8537f62d5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('obj', sa.String(length=30), nullable=True),
    sa.Column('trunk_username', sa.String(length=20), nullable=True),
    sa.Column('trunk_password', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vats')
    # ### end Alembic commands ###
